PATH_RAW_PDF: "data/raw"
PATH_EXTRACTION: "data/extraction"
COLLECTION_NAME: "docs"
PDF_PARSER: "PyPDFLoader"
EMBEDDING_MODEL: "BAAI/bge-small-en-v1.5"
TOKENIZER_CHUNK_SIZE: 1000
TOKENIZER_CHUNK_OVERLAP: 150
